### PR TITLE
LRU Cache

### PR DESCRIPTION
**Pull request by lastcanal**
This implements an in-memory LRU cache for HTTP and WebSocket requests.

### CODE REVIEW

**Comment by evoskuil** [comment]
Hi @lastcanal, this PR showed up in my notifications today. I'm not sure how, but cool stuff!

**Comment by lastcanal** [comment]
Thanks! I've got the server processing over 20k requests per second on my laptop with all CPU cores pegged at 100%. 3ms response time for headers when they are in the cache. 

```
➜  wrk2 git:(master) ./wrk -t4 -c200 -d10s -R40000 http://127.0.0.1:9090/api/v1/blockchain/block_header/420000
Running 10s test @ http://127.0.0.1:9090/api/v1/blockchain/block_header/420000
  4 threads and 200 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.77s     1.19s    4.68s    58.09%
    Req/Sec        nan       nan   0.00      0.00%
  232391 requests in 10.00s, 97.33MB read
Requests/sec:  23237.76
Transfer/sec:      9.73MB
```

**Comment by evoskuil** [comment]
Nice, is that through your API on a stock v3 server?

**Comment by lastcanal** [comment]
It's through our API connected to a stock v2.4.0 server. I'm planning on bootstrapping a fresh v3 server over the weekend to see how it does.

**Comment by evoskuil** [comment]
Master has a few rough edges at the moment. I've been making a lot of changes and have broken a couple of things. Performance is significantly better in a number of areas. It's now possible to sync the full mainnet chain in about 15 minutes and validation speed is also dramatically faster. There are also significant benefits to query performance, including a reduction of write locking during reorg (including each single new block) from ~20 secs (which generally causes queries to time out) to ~10ms. The server (zmq) query workers have also been completely optimized for performance. Feel free to contact me on IRC and make sure you are on the mailing list!

**Comment by lastcanal** [comment]
That is amazing. I've noticed some timeouts with version2 when a new block arrives; it's great you've managed to parallelize the validation! We are now caching transactions that are sent via the transaction subscription, which will ease pressure on bs when fetching a new block's transactions. Keep up the good work :)

**Comment by evoskuil** [comment]
It's worth noting that transaction hashes do not uniquely identify transactions. Hash collisions are allowed in Bitcoin (see BIP30). Our client-server interface does not allow for this, returning only the most recent of a given hash, although we handle it properly in v3 in terms of validation. Something to consider when caching.

**Pull request merged**
